config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
    resources 'address',except: :show
    resources :invites
    root :to => 'home#index'
    get 'profile', to: 'home#me'

    namespace :users, path: '' do
      resources 'lotteries', only: [:show, :index, :create]
      resources :shops
      resources :orders, only: [:new, :create] do
        put :cancel
      end
      resources :winners, only: [:show, :update]
      resources :shares
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root :to => 'home#index'
      devise_for :users, controllers: { sessions: 'admin/sessions' }

      resources :userlists do
        resources :increase, :deduct, :bonus, only: [:create, :new]
      end

      resources :categories
      resources :offers
      resources :newstickers
      resources :banners
      resources :invites, only: :index
      resources :orders do
        put :submit, :cancel, :pay
      end
      resources :items do
        put :start, :pause, :end, :cancel
      end

      resources :bets do
        put :cancel
      end

      resources :winners do
        put :submit, :pay,:ship, :deliver, :publish, :remove_publish
      end
    end
  end
end

app/controllers/admin/deduct_controller.rb
class Admin::DeductController < AdminController
  before_action :set_user

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.genre = :deduct
    @order.user = @user
    if @order.save
      if @order.may_pay? && @order.pay!
        flash[:alert]= 'Deducted successfully!'
      else
        flash[:alert]= 'Failed to deduct, user coin cannot be less than zero'
        @order.cancel!
      end
      redirect_to new_admin_userlist_deduct_path
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:coin, :remarks)
  end

  def set_user
    @user = User.find params[:userlist_id]
  end
end

app/views/admin/deduct/new.html.erb
<%= render "layouts/navbar_admin/navadmin" %>
<div class="main">
  <h1>Ballance operate</h1>
  <%= render "layouts/alert_msg/alert_notice" %>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
              <%= link_to "Increase", new_admin_userlist_increase_path(@user), class: "nav-link " if admin_user_signed_in? %>
            </li>
            <li class="nav-item">
              <%= link_to "Deduct", new_admin_userlist_deduct_path(@user), class: "nav-link active" if admin_user_signed_in? %>
            </li>
            <li class="nav-item">
              <%= link_to "Bonus",new_admin_userlist_bonu_path(@user), class: "nav-link " if admin_user_signed_in? %>
            </li>
          </ul>
        </div>
        <div class="card-body">
          <%= form_for @order, url: admin_userlist_deduct_index_path(@user), method: :post do |f| %>
            <div>
              <%= f.label :coin %>
              <%= f.number_field :coin, min:1, value:1, class: 'form-control' %>
            </div>

            <div>
              <%= f.label :remarks %>
              <%= f.text_field :remarks,required: true, class: 'form-control' %>
            </div>

            <%= f.submit "Save", data:{confirm:'Are you sure do you want to deduct the coins of this user?'}, class: 'btn btn-primary mt-2', style: 'margin-buttom: 10px; width: auto;' %><br><br>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card">
        <div class="card-body">
          <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Username</span>
            <input type="text" class="form-control" value="<%=@user.username %>" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
          </div>

          <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Promoter name</span>
            <input type="text" class="form-control" value="<%= @user.parent&.username %>" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
          </div>

          <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Coins</span>
            <input type="text" class="form-control" value="<%= @user.coins %>" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" readonly>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>