config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
    resources 'address',except: :show
    resources :invites
    root :to => 'home#index'
    get 'profile', to: 'home#me'

    namespace :users, path: '' do
      resources 'lotteries', only: [:show, :index, :create]
      resources :shops
      resources :orders, only: [:new, :create] do
        put :cancel
      end
      resources :winners, only: [:show, :update]
      resources :shares
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root :to => 'home#index'
      devise_for :users, controllers: { sessions: 'admin/sessions' }

      resources :userlists do
        resources :increase, :deduct, :bonus, only: [:create, :new]
      end

      resources :categories
      resources :offers
      resources :newstickers
      resources :banners
      resources :invites, only: :index
      resources :orders do
        put :submit, :cancel, :pay
      end
      resources :items do
        put :start, :pause, :end, :cancel
      end

      resources :bets do
        put :cancel
      end

      resources :winners do
        put :submit, :pay,:ship, :deliver, :publish, :remove_publish
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :offer, optional: true

  enum genre: [:deposit, :increase, :deduct, :bonus, :share]

  validates :amount, numericality: { greater_than: 0 }, if: :deposit?
  validates :amount, numericality: { greater_than_or_equal: 0 }, unless: :deposit?


  after_create :generate_serial_number

  include AASM
  aasm column: :state do
    state :pending, initial: true
    state :submitted, :cancelled, :paid

    event :submit do
      transitions from: :pending, to: :submitted
    end

    event :cancel do
      transitions from: [:pending, :submitted], to: :cancelled
      transitions from: :paid, to: :cancelled, after: :cancel_user_coin, guard: :coin_less_that_user_coins?
    end

    event :pay, after: :update_user_coin_on_pay do
      transitions from: :submitted, to: :paid, after: :total_deposit
      transitions from: :pending, to: :paid, guard: :unless_coin_less_that_user_coins?
    end
  end

  def cancel_user_coin
    if deduct?
      user.update(coins: user.coins +  coin)
    else
      user.update(coins: user.coins - coin)
    end
  end

  def update_user_coin_on_pay
    if deduct?
      user.update(coins: user.coins - coin)
    else
      user.update(coins: user.coins + coin)
    end
  end

  def total_deposit
    user.update(total_deposit: user.total_deposit + coin)
  end

  def coin_less_that_user_coins?
    return true if deduct?
    return true if (user.coins >= coin)
    errors.add(:base, "You deducted more coins than the user's total coins")
    false
  end

  def unless_coin_less_that_user_coins?
    return true unless deduct?
    return true if (user.coins >= coin)
    errors.add(:base, "Unless you deducted more coins than the user's total coins")
    false
  end

  def generate_serial_number
    ActiveRecord::Base.connection.execute("UPDATE `orders` SET `orders`.`serial_number` = CONCAT(DATE_FORMAT(CONVERT_TZ(orders.created_at, '+00:00', '+8:00'), '%y%m%d'),'-',#{id},'-',#{user.id},'-',
                                                    (SELECT LPAD(count(*), 4, 0)
                                                     FROM `orders` where `orders`.`user_id` = #{user.id}))
                                                     WHERE orders.id = #{id}")
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_order, except: :index

  def index
    @orders = Order.includes(:user, :offer).order(id: :desc)

    @total_coins = @orders.map(&:coin).sum
    @total_amount = @orders.map(&:amount).sum

    @orders = @orders.where(user: { email: params[:email] }) if params[:email].present?
    @orders = @orders.where(offer: { name: params[:offer] }) if params[:offer].present?
    @orders = @orders.where(serial_number: params[:serial_number]) if params[:serial_number].present?
    @orders = @orders.where(genre: params[:genre]) if params[:genre].present?
    @orders = @orders.where(state: params[:state]) if params[:state].present?
    @orders = @orders.where(created_at: params[:start_date].to_datetime..params[:end_date].to_datetime) if params[:start_date].present? && params[:end_date].present
    @subtotal_coins = @orders.map(&:coin).sum
    @subtotal_amount = @orders.map(&:amount).sum
  end



  def submit
    if @order.submit!
      flash[:notice] = "Submit successfully!"
    else
      flash[:alert] = "Failed to start!"
    end
    redirect_to admin_orders_path
  end

  def cancel
    if @order.cancel!
      flash[:notice] = "Cancelled successfully!"
    else
      flash[:alert] = "Failed to cancel!"
    end
    redirect_to admin_orders_path
  end

  def pay
    if @order.pay!
      flash[:notice] = "Payed successfully!"
    else
      flash[:alert] = "Failed to pay!"
    end
    redirect_to admin_orders_path
  end

  private

  def set_order
    @order = Order.find params[:order_id]
  end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
  before_action :authenticate_user!, only: :create
  def cancel
    @order = Order.find params[:order_id]
    if @order.cancel!
      flash[:alert] = "Cancelled successfully!"
    else
      flash[:alert] = "Failed to cancel!"
    end
    redirect_to profile_path
  end

  def create
    @offer = Offer.active.find(params[:offer_id])
    @order = Order.new
    @order.amount = @offer.amount
    @order.coin = @offer.coin
    @order.user = current_user
    @order.genre = :deposit
    @order.offer = @offer
    if @order.save
      if @order.may_submit? && @order.submit!
        flash[:notice]= 'Order submit successfully!'
      else
        flash[:alert]= 'transaction failed'
        @order.cancel!
      end
      redirect_to users_shops_path
    else
      render :new
    end
  end
end

app/views/admin/orders/index.html.erb
<%= render "layouts/navbar_admin/navadmin" %>
<br>
<style>
    .main .cont {
        width: 45%;
        display: inline-block
    }
</style>

<div class="main">
  <%= render "layouts/alert_msg/alert_notice" %>
  <div class="border p-3">
    <%= form_tag({ url: admin_winners_path }, { method: :get }) do %>
      <div>
        <%= label_tag :find_by %>:
      </div>

      <div class="cont ">
        <%= label_tag :serial_number %>
        <%= text_field_tag :serial_number, '', class: "form-control w-100" %>
      </div>

      <div class="cont">
        <%= label_tag :email %>
        <%= text_field_tag :email, '', class: "form-control w-100" %>
      </div>

      <div class="cont">
        <%= label_tag :state %>
        <%= select_tag :state, options_for_select(Order.aasm.states.map(&:name), params[:state]), { prompt: 'Select one', class: "form-select dropdown w-100 " } %>
      </div>

      <div class="cont">
        <%= label_tag :genre %>
        <%= select_tag :genre, options_for_select(Order.genres.map), { prompt: 'Select one', class: "form-select dropdown w-100 " } %>
      </div>

      <div class="cont">
        <%= label_tag :offer %>
        <%= select_tag :offer, options_for_select(Offer.all.map(&:name)), { prompt: 'Select one', class: "form-select dropdown w-100 " } %>
      </div>
      <br><br>
      <div>
        <%= label_tag :date_created %>:
      </div>

      <div class="cont">
        <%= label_tag :start_date %>
        <%= datetime_field_tag :start_date, '', class: "form-control w-100" %>
      </div>

      <div class="cont">
        <%= label_tag :end_date %>
        <%= datetime_field_tag :end_date, '', class: "form-control w-100" %>
      </div>
      <br><br>
      <div>
        <%= submit_tag :Search, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <br>

  <table class="table table-striped border border-success">
    <h2 scope="col">Subtotal and Total of Orders</h2>
    <thead>
    <tr>
      <th scope="col">Subtotal coin</th>
      <th scope="col">Subtotal amount</th>

      <th scope="col">Total coin</th>
      <th scope="col">Total amount</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @subtotal_coins %></td>
      <td><%= @subtotal_amount %></td>

      <td><%= @total_coins %></td>
      <td><%= @total_amount %></td>
    </tr>
    </tbody>

  </table>

  <table class="table table-striped border border-success">
    <h2 scope="col">All Orders</h2>
    <thead>
    <tr>
      <th scope="col">User</th>
      <th scope="col">Offer</th>
      <th scope="col">Serial number</th>
      <th scope="col">State</th>
      <th scope="col">Amount</th>
      <th scope="col">Coin</th>
      <th scope="col">Remarks</th>
      <th scope="col">Genre</th>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <% @orders.each do |order| %>
      <tbody>
      <tr>
        <th scope="row"><%= order.user.email %></th>
        <td><%= order.offer&.name %></td>
        <td><%= order.serial_number %></td>
        <td><%= order.state %></td>
        <td><%= order.amount %></td>
        <td><%= order.coin %></td>
        <td><%= order.remarks %></td>
        <td><%= order.genre %></td>
        <td>
          <%= button_to "submit", admin_order_submit_path(order), data:{confirm:'Are you sure do you want to submit?'}, class: "btn btn-primary", style: "width: 80px;", method: :put if order.may_submit? %>
          <%= button_to "cancel", admin_order_cancel_path(order), data:{confirm:'Are you sure do you want to cancel?'}, class: "btn btn-primary", style: "width: 80px;", method: :put if order.may_cancel? %>
          <%= button_to "pay", admin_order_pay_path(order), data:{confirm:'Are you sure do you want to pay?'}, class: "btn btn-primary", style: "width: 80px;", method: :put if order.may_pay? %>
        </td>
      </tr>
      </tbody>
    <% end %>
  </table>
</div>