config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
    resources 'address',except: :show
    resources :invites
    root :to => 'home#index'
    get 'profile', to: 'home#me'

    namespace :users, path: '' do
      resources 'lotteries', only: [:show, :index, :create]
      resources :shops
      resources :orders, only: [:new, :create] do
        put :cancel
      end
      resources :winners, only: [:show, :update]
      resources :shares
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root :to => 'home#index'
      devise_for :users, controllers: { sessions: 'admin/sessions' }

      resources :userlists do
        resources :increase, :deduct, :bonus, only: [:create, :new]
      end

      resources :categories
      resources :offers
      resources :newstickers
      resources :banners
      resources :invites, only: :index
      resources :orders do
        put :submit, :cancel, :pay
      end
      resources :items do
        put :start, :pause, :end, :cancel
      end

      resources :bets do
        put :cancel
      end

      resources :winners do
        put :submit, :pay,:ship, :deliver, :publish, :remove_publish
      end
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController

  def index;  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!,except: :index

  def index
    @winners = Winner.published.limit(5)
  end

  def me
    @orders = current_user.orders.includes(:user).order(id: :desc) if params[:activities] == 'orders' || params[:activities].blank?
    @bets = current_user.bets.includes(:user) if params[:activities] == 'bets'
    @winners = current_user.winners.includes(:user) if params[:activities] == 'winners'
    @children = current_user.children if params[:activities] == 'children'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= render "layouts/imgslider/imgslider" %>

<div class="text-center">
  <p>Winners Feedback</p>
  <% @winners.each do |winner| %>
    <div style="width: 10%;display: inline-block;">
      <%= image_tag winner.picture.url, class: "img-thumbnail ",style:" margin: 1px;" if winner.picture? %>
    </div>
  <% end %>
  <div style="width: 10%;display: inline-block;">
    <%= link_to 'More..', users_shares_path, class: 'btn mb-4', style:"width: 70px;"  %>
  </div>
</div> <br>
<div class="text-center" style="margin-bottom: 120px;">
  <p>Comming Soon</p>
  <img src="f7ebd86ff10d7d738d975f227a591600.jpeg" class="rounded" style="height: 200px; width: 200px;">
  <img src="f7ebd86ff10d7d738d975f227a591600.jpeg" class="rounded" style="height: 200px; width: 200px;">
  <img src="f7ebd86ff10d7d738d975f227a591600.jpeg" class="rounded" style="height: 200px; width: 200px;">
  <img src="f7ebd86ff10d7d738d975f227a591600.jpeg" class="rounded" style="height: 200px; width: 200px;">
</div>


<%= render "layouts/sharednav/nav" %>

app/views/home/me.html.erb
<style>
    .user-profile {
        border: 1px solid;
        padding: 10px;
        margin: auto;
        width: 60%;
        margin-top: 100px;
    }

    .full-width {
        width: 100%;
        text-align: center;
        padding: 5px;
    }

    .border1 {
        width: 60%;
        margin: auto;
    }

</style>

<div class="user-profile">
  <div>
    <%= render "layouts/alert_msg/alert_notice" %>
  </div>
  <div><%= image_tag current_user&.avatar.url if current_user.avatar? %></div>
  <div><p>Username : <%= current_user.username %></p></div>
  <div><p>Email : <%= current_user.email %></p></div>
  <div><p>Coins : <%= current_user.coins %></p></div>
  <button class="full-width">Cash in now</button>
  <br>
  <br>
  <div class="full-width">
    <%= link_to "Me", edit_user_registration_path, { class: "btn btn-primary btn-lg btn-block", style: "width: 49%;" } if user_signed_in? %>
    <%= link_to "Address", address_index_path, { class: "btn btn-primary btn-lg btn-block", style: "width: 49%;" } if user_signed_in? %>
  </div>
</div>
<br>
<div class="border1">
  <%= link_to "Order History", profile_path(activities: 'orders'), { class: "btn btn-primary" } if user_signed_in? %>
  <%= link_to "Lottery History", profile_path(activities: 'bets'), { class: "btn btn-primary" } if user_signed_in? %>
  <%= link_to "Winning History", profile_path(activities: 'winners'), { class: "btn btn-primary" } if user_signed_in? %>
  <%= link_to "Invitation History", profile_path(activities: 'children'), { class: "btn btn-primary" } if user_signed_in? %>
</div>
<br>
<div class="border1">
  <% @orders&.each do |order| %>
    <div class="border w-100 mx-auto p-3">
      <p>Serial number: <%= order.serial_number %></p>
      <p>Amount: <%= order.amount %></p>
      <p>Coin: <%= order.coin %></p>
      <p>Created at: <%= order.created_at %></p>
      <p>State: <%= order.state %></p>
      <%= link_to "Cancel", users_order_cancel_path(order), method: :put, class: 'btn btn-warning' if order.submitted? %>
    </div>
    <br>
  <% end %>
</div>
<br>

<div class="border1">
  <% @bets&.each do |bet| %>
    <div class="border w-100 mx-auto p-3">
      <p>Batch count: <%= bet.batch_count %></p>
      <p>Coins: <%= bet.coins %></p>
      <p>State: <%= bet.state %></p>
      <p>Serial number: <%= bet.serial_number %></p>
    </div>
    <br>
  <% end %>
</div>
<br>

<div class="border1">
  <% @winners&.each do |winner| %>
    <div class="border w-100 mx-auto p-3">
      <p>Item name: <%= winner.item.name %></p>
      <p>Address: <%= concat_address(winner.address) %></p>
      <p>Batch count: <%= winner.item_batch_count %></p>
      <p>State: <%= winner.state %></p>
      <%= link_to "Claim", users_winner_path(winner), class: 'btn btn-warning' if winner.may_claim? %>
      <%= link_to "Share", users_share_path(winner), class: 'btn btn-warning' if winner.may_share? %>
    </div>
    <br>
  <% end %>
</div>
<br>
<div class="border1">
  <% @children&.each do |children| %>
    <div class="border w-100 mx-auto p-3">
      <p>Name: <%= children.email %></p>
      <p>Phone: <%= children.phone %></p>
      <p>Username: <%= children.username %></p>
    </div>
    <br>
  <% end %>
</div><br><br><br><br><br>
<%= render "layouts/sharednav/nav" %>