config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
    resources 'address',except: :show
    resources :invites
    root :to => 'home#index'
    get 'profile', to: 'home#me'

    namespace :users, path: '' do
      resources 'lotteries', only: [:show, :index, :create]
      resources :shops
      resources :orders, only: [:new, :create] do
        put :cancel
      end
      resources :winners, only: [:show, :update]
      resources :shares
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root :to => 'home#index'
      devise_for :users, controllers: { sessions: 'admin/sessions' }

      resources :userlists do
        resources :increase, :deduct, :bonus, only: [:create, :new]
      end

      resources :categories
      resources :offers
      resources :newstickers
      resources :banners
      resources :invites, only: :index
      resources :orders do
        put :submit, :cancel, :pay
      end
      resources :items do
        put :start, :pause, :end, :cancel
      end

      resources :bets do
        put :cancel
      end

      resources :winners do
        put :submit, :pay,:ship, :deliver, :publish, :remove_publish
      end
    end
  end
end

app/models/winner.rb
class Winner < ApplicationRecord
  belongs_to :item, optional: true
  belongs_to :bet, optional: true
  belongs_to :user, optional: true
  belongs_to :address, optional: true

  mount_uploader :picture, AvatarUploader

  include AASM
  aasm column: :state do
    state :won, initial: true
    state :won, :claimed, :submitted, :paid, :shipped, :delivered, :shared, :published, :remove_published

    event :claim do
      transitions from: :won, to: :claimed
    end

    event :submit do
      transitions from: :claimed, to: :submitted
    end

    event :pay do
      transitions from: :submitted, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipped
    end

    event :deliver do
      transitions from: :shipped, to: :delivered
    end

    event :share do
      transitions from: :delivered, to: :shared
    end

    event :publish do
      transitions from: [:shared, :remove_published], to: :published
    end

    event :remove_publish do
      transitions from: :published, to: :remove_published
    end
  end
end

app/controllers/admin/winners_controller.rb
class Admin::WinnersController < AdminController
  before_action :set_winner, except: :index

  def index
    @winners = Winner.includes(:bet, :user, :item)
    @winners = @winners.where(bet: { serial_number: params[:serial_number] }) if params[:serial_number].present?
    @winners = @winners.where(user: { email: params[:email] }) if params[:email].present?
    @winners = @winners.where(state: params[:state]) if params[:state].present?
    @winners = @winners.where(created_at: params[:start_date].to_datetime..params[:end_date].to_datetime) if params[:start_date].present? && params[:end_date].present?
  end

  def submit
    if @winner.submit!
      flash[:notice] = "Submitted successfully"
    else
      flash[:alert] = "Failed to submit"
    end
    redirect_to admin_winners_path
  end

  def pay
    if @winner.pay!
      flash[:notice] = "Paid successfully"
    else
      flash[:alert] = "Failed to pay"
    end
    redirect_to admin_winners_path
  end

  def ship
    if @winner.ship!
      flash[:notice] = "Shipped successfully"
    else
      flash[:alert] = "Failed to ship"
    end
    redirect_to admin_winners_path
  end

  def deliver
    if @winner.deliver!
      flash[:notice] = "Delivered successfully"
    else
      flash[:alert] = "Failed to deliver"
    end
    redirect_to admin_winners_path
  end

  def publish
    if @winner.publish!
      flash[:notice] = "Published successfully"
    else
      flash[:alert] = "Failed to publish"
    end
    redirect_to admin_winners_path
  end

  def remove_publish
    if @winner.remove_publish!
      flash[:alert] = "Removed publish successfully"
    else
      flash[:alert] = "Failed to removed publish"
    end
    redirect_to admin_winners_path
  end

  private

  def set_winner
    @winner = Winner.find params[:winner_id]
  end
end

app/controllers/users/winners_controller.rb
class Users::WinnersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner
  before_action :set_address, only: :update

  def show; end

  def update
    if @winner.claim!
      if @winner.update(address: @address)
        flash[:notice] = "Updated Successfully!"
        redirect_to profile_path
      else
        render :edit
      end
    else
      render :edit
    end
  end

  private

  def set_winner
    @winner = Winner.where(user: current_user).find(params[:id])
  end

  def set_address
    @address = Address.where(user: current_user).find_by_id(params.dig(:winner,:address))
    if @address.blank?
      flash[:alert] = "You don't have any addresses"
      redirect_to address_index_path
    end
  end

end

app/helpers/winners_helper.rb
module WinnersHelper
  def concat_address(address)
    return if address.nil?
    "#{address.street_address}, #{address.barangay.name}, #{address.city.name}, #{address.province.name}, #{address.region.name}"
  end
end

app/views/admin/winners/index.html.erb
<%= render "layouts/navbar_admin/navadmin" %> <br>
<div class="main">
  <div class="border p-3">
    <%= form_tag({ url: admin_winners_path }, { method: :get }) do %>
      <div>
        <%= label_tag :find_by %>
      </div>

      <div class="d-inline p-2">
        <%= label_tag :serial_number %>
        <%= text_field_tag :serial_number, '' %>
      </div>

      <div class="d-inline p-2">
        <%= label_tag :email %>
        <%= text_field_tag :email, '' %>
      </div>

      <div class="d-inline p-2">
        <%= label_tag :state %>
        <%= text_field_tag :state, '' %>
      </div>
      <br> <br>

      <div>
        <%= label_tag :date_created %>
      </div>

      <div class="d-inline p-2">
        <%= label_tag :start_date %>
        <%= datetime_field_tag :start_date, '' %>
      </div>

      <div class="d-inline p-2">
        <%= label_tag :end_date %>
        <%= datetime_field_tag :end_date, '' %>
      </div>

      <div>
        <%= submit_tag :Search, class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <table class="table table-striped border border-success">
    <h2 scope="col">All Bets</h2>
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Serial number</th>
      <th scope="col">Email</th>
      <th scope="col">Address</th>
      <th scope="col">State</th>
      <th scope="col">Batch count</th>
      <th scope="col">Created at</th>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <% @winners.each do |winner| %>
      <tbody>
      <tr>
        <th scope="row"><%= winner.id %></th>
        <td><%= winner.bet.serial_number %></td>
        <td><%= winner.user.email %></td>
        <td><%= concat_address(winner.address)%></td>
        <td><%= winner.state %></td>
        <td><%= winner.item_batch_count %></td>
        <td><%= winner.created_at %></td>
        <td>
          <%= button_to "Submit", admin_winner_submit_path(winner), data:{confirm:'Are you sure do you want to submit?'}, class: "btn btn-primary", style:"width: 80px;", method: :put if winner.may_submit? %>
          <%= button_to "Pay",  admin_winner_pay_path(winner), data:{confirm:'Are you sure do you want to pay?'}, class: "btn btn-primary", style:"width: 80px;",method: :put if winner.may_pay? %>
          <%= button_to "Ship",  admin_winner_ship_path(winner), data:{confirm:'Are you sure do you want to ship?'},  class: "btn btn-primary", style:"width: 80px;",method: :put if winner.may_ship? %>
          <%= button_to "Deliver",  admin_winner_deliver_path(winner), data:{confirm:'Are you sure do you want to deliver?'}, class: "btn btn-primary", style:"width: 80px;",method: :put if winner.may_deliver? %>
          <%= button_to "Publish",   admin_winner_publish_path(winner), data:{confirm:'Are you sure do you want to publish?'}, class: "btn btn-primary", style:"width:  80px;",method: :put if winner.may_publish? %>
          <%= button_to "Remove publish",  admin_winner_remove_publish_path(winner), data:{confirm:'Are you sure do you want to remove publish?'}, class: "btn btn-primary", style:"width: 150px;",method: :put if winner.may_remove_publish? %>
        </td>
      </tr>
      </tbody>
    <% end %>
  </table>
</div>